sudo: false
cache:
  directories:
  - $PWD/vendor
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
env:
  - COMPOSER_ROOT_VERSION=dev-master
install:
  - composer install --prefer-dist
script:
  - bin/spectre spec
